### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Nagisa9029** [Nagisa9029/chat-space#11]
# IPアドレス
18.178.71.234

**Comment by mo1015** [comment]
仲村さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○「Create Account」「Log in」「Edit Account」の文字色をカリキュラムと同じにしましょう**
参考カリキュラム：https://master.tech-camp.in/curriculums/4265

↓参考カリキュラム画像
<img width="1276" alt="e649933b18f327811ba5971c9e1d748b" src="https://user-images.githubusercontent.com/62644781/84006366-8f7b2180-a9a9-11ea-86b5-a051b9036129.png">

**○チャットグループ編集ページで「更新する」ボタンを押すと、グループページが表示されるようにしましょう**
→現状トップページが表示されます


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Nagisa9029** [comment]
以下、2点修正しました
・「Create Account」「Log in」「Edit Account」の文字色を【Black】に修正
・チャットグループ編集ページ【更新後】の表示Viewをグループページに修正


## 補足
応用カリキュラム内で、ChatSpace（見本）へのリンクがいくつかあるのですが、２パターンあるようです。
```
https://chatspace-2020.herokuapp.com/
https://chat-space-sample.herokuapp.com/
```
私は、
>https://chatspace-2020.herokuapp.com/

を見本に実装しておりました。
今後、他の受講生も迷うかもしれません。

**Comment by mo1015** [comment]
再提出ありがとうございます！下記修正の確認ができました！
**・「Create Account」「Log in」「Edit Account」の文字色を【Black】に修正
・チャットグループ編集ページ【更新後】の表示Viewをグループページに修正**
丁寧なコメントありがとうございます！LGTMとさせていただきます🎉

また、見本ChatSpaceの共有誠にありがとうございます。
混乱させてしまい、大変失礼致しました。
該当箇所の確認をし社内で対応させていただきます。
